version: "3"

services:
  db:
    image: postgres:15.4
    container_name: embryovision.db
    environment:
      - POSTGRES_USER=cyberbiba2000
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=embryovision
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$$POSTGRES_PASSWORD psql -U $$POSTGRES_USER -h db -lqt | grep -wo $$POSTGRES_DB || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"

