alias r := run
alias s := stop
alias m := migrate
alias mm := makemigrations


run:
   docker-compose up -d db
   ./manage.py runserver localhost:8000

up:
   docker-compose up

stop:
   docker-compose stop

rebuild:
   docker-compose up --build

makemigrations *args:
   ./manage.py makemigrations {{args}}
    
migrate:
   ./manage.py migrate

